// <auto-generated />
namespace WEB_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class checkUp2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(checkUp2));
        
        string IMigrationMetadata.Id
        {
            get { return "202311300809523_checkUp2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
