// <auto-generated />
namespace WEB_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class check3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(check3));
        
        string IMigrationMetadata.Id
        {
            get { return "202311281903027_check3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
